### ISSUE TITLE
Systemjs： there something wrong with your options

### ISSUE THREAD

**Issue by ntfs32** [Gbuomprisco/ng2-tag-input#197]
not add anything to paths，just add 
```javascript
    'ng2-tag-input': {
        main: 'dist/ng2-tag-input.bundle.js',
        format: 'cjs',
    },
    'ng2-material-dropdown': {
        defaultExtension: 'js',
        main: 'dist/ng2-dropdown.bundle.js',
        format: 'cjs',
    },
    'ng2-tag-input/modules/components/tag-input.template.html': {
        defaultJSExtension: false
    }
```

but get error:
```
Reduce of empty array with no initial value ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Reduce of empty array with no initial value
```
what should I do?
 thanks.

**Comment by Gbuomprisco** [comment]
Sorry, but more information are needed. I am not even sure the problem is in the configuration.

**Comment by ntfs32** [comment]
system config：
```javascript
 SYSTEM_BUILDER_CONFIG: any = {
    defaultJSExtensions: true,
    base: this.PROJECT_ROOT,
    packageConfigPaths: [
      join('node_modules', '*', 'package.json'),
      join('node_modules', '@angular', '*', 'package.json')
    ],
    paths: {
      [join(this.TMP_DIR, 'app', '*')]: `${this.TMP_DIR}/app/*`,
      '*': 'node_modules/*',
      'ng2-tag-input': 'node_modules/ng2-tag-input'
    },
    packages: {
      '@angular/common': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/compiler': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/core/testing': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/core': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/forms': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/http': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser-dynamic': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/router': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      'ng2-date-picker': {
        main: 'bin/app/index.js',
        defaultExtension: 'js'
      },
      'ng2-select': {
        main: 'ng2-select.js',
        defaultExtension: 'js'
      },
      'rxjs': {
        main: 'Rx.js',
        defaultExtension: 'js'
      },
      'ng2-tag-input': {
        main: 'dist/ng2-tag-input.bundle.js',
        format: 'cjs',
      },
      'ng2-material-dropdown': {
        defaultExtension: 'js',
        main: 'dist/ng2-dropdown.bundle.js',
        format: 'cjs',
      },
      'ng2-tag-input/modules/components/tag-input.template.html': {
        defaultJSExtension: false
      }
    }
  };
```

module code：
```javascript
import { TagInputModule } from 'ng2-tag-input';
...
 imports: [
        RouterModule,
        FormsModule,
        CommonModule,
        AlertModule,
        ButtonsModule,
      ...
        TagInputModule,
    ],
```

view code:
```javascript
<fieldset class="form-group">
          <label class="col-sm-2 control-label">支持参数</label>
          <div class="col-sm-10">
            <tag-input [ngModel]="['Javascript', 'Typescript']"></tag-input>
          </div>
        </fieldset>
```

before add view code ,the error get.

```
(http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10304:94)
    at Array.forEach (native)
    at _AnimationBuilder.visitAnimationEntry (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10304:32)
    at AnimationEntryAst.visit (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:9464:26)
    at _AnimationBuilder.build (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10340:33)
    at eval (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10138:47)
    at Array.forEach (native) TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at _AnimationBuilder.visitAnimationStateTransition (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10263:74)
    at AnimationStateTransitionAst.visit (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:9495:26)
    at eval (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10304:94)
    at Array.forEach (native)
    at _AnimationBuilder.visitAnimationEntry (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10304:32)
    at AnimationEntryAst.visit (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:9464:26)
    at _AnimationBuilder.build (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10340:33)
    at eval (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:10138:47)
    at Array.forEach (native)
consoleError @ zone.js?1487238176472:344
zone.js?1487238176472:346 Error: Uncaught (in promise): TypeError: Reduce of empty array with no initial value
    at resolvePromise (zone.js?1487238176472:418)
    at resolvePromise (zone.js?1487238176472:403)
    at zone.js?1487238176472:451
    at ZoneDelegate.invokeTask (zone.js?1487238176472:225)
    at Zone.runTask (zone.js?1487238176472:125)
    at drainMicroTaskQueue (zone.js?1487238176472:357)
    at XMLHttpRequest.ZoneTask.invoke (zone.js?1487238176472:297)
consoleError @ zone.js?1487238176472:346
```

it`s so lang ,thinks

 :) :) :)

**Comment by Gbuomprisco** [comment]
Hi @ntfs32,

it looks like the issue is related to the animations module. Can you post here your package.json dependencies?

**Comment by ntfs32** [comment]
```json
"devDependencies": {
    "@angular/compiler-cli": "0.6.1",
    "@angular/platform-server": "2.0.0",
    "@angular/tsc-wrapped": "0.3.0",
    "@types/async": "2.0.31",
    "@types/browser-sync": "0.0.32",
    "@types/connect-livereload": "0.5.29",
    "@types/core-js": "0.9.32",
    "@types/express": "4.0.32",
    "@types/gulp": "3.8.31",
    "@types/gulp-load-plugins": "0.0.27",
    "@types/gulp-protractor": "1.0.28",
    "@types/gulp-sass": "0.0.28",
    "@types/gulp-shell": "0.0.28",
    "@types/gulp-util": "3.0.28",
    "@types/jasmine": "2.2.33",
    "@types/node": "6.0.38",
    "@types/protractor": "1.5.18",
    "@types/rimraf": "0.0.27",
    "@types/run-sequence": "0.0.27",
    "@types/selenium-webdriver": "2.44.*",
    "@types/systemjs": "0.19.30",
    "@types/yargs": "0.0.30",
    "@types/zone.js": "0.0.26",
    "async": "2.0.1",
    "autod": "^2.7.1",
    "autoprefixer": "6.3.7",
    "browser-sync": "2.13.0",
    "codelyzer": "1.0.0-beta.0",
    "colorguard": "1.2.0",
    "compression": "1.6.2",
    "connect": "3.4.1",
    "connect-history-api-fallback": "1.3.0",
    "connect-livereload": "0.5.4",
    "cssnano": "3.7.3",
    "deep-extend": "0.4.1",
    "doiuse": "2.4.1",
    "event-stream": "3.3.3",
    "express": "~4.14.0",
    "express-history-api-fallback": "2.0.0",
    "extend": "3.0.0",
    "gulp": "3.9.1",
    "gulp-cached": "1.1.0",
    "gulp-clean-css": "2.0.11",
    "gulp-concat": "2.6.0",
    "gulp-concat-css": "2.3.0",
    "gulp-filter": "4.0.0",
    "gulp-inject": "4.1.0",
    "gulp-inline-ng2-template": "3.0.1",
    "gulp-load-plugins": "1.2.4",
    "gulp-plumber": "~1.1.0",
    "gulp-postcss": "6.1.1",
    "gulp-progeny": "0.3.1",
    "gulp-protractor": "2.4.0",
    "gulp-replace": "0.5.4",
    "gulp-sass": "2.3.2",
    "gulp-sass-lint": "1.2.0",
    "gulp-sourcemaps": "2.0.0-alpha",
    "gulp-template": "4.0.0",
    "gulp-tslint": "6.0.1",
    "gulp-typescript": "2.13.6",
    "gulp-uglify": "2.0.0",
    "gulp-util": "3.0.7",
    "gulp-watch": "4.3.8",
    "is-ci": "1.0.9",
    "isstream": "0.1.2",
    "jasmine-core": "~2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "~0.13.22",
    "karma-chrome-launcher": "~1.0.1",
    "karma-coverage": "1.1.0",
    "karma-jasmine": "~1.0.2",
    "karma-mocha-reporter": "2.0.4",
    "merge-stream": "1.0.0",
    "open": "0.0.5",
    "postcss-reporter": "1.4.1",
    "protractor": "3.3.0",
    "remap-istanbul": "0.6.4",
    "rimraf": "2.5.3",
    "run-sequence": "1.2.2",
    "semver": "5.3.0",
    "serve-static": "1.11.1",
    "slash": "~1.0.0",
    "stylelint": "7.0.2",
    "stylelint-config-standard": "11.0.0",
    "systemjs-builder": "0.15.31",
    "tildify": "1.2.0",
    "traceur": "0.0.111",
    "ts-node": "1.0.0",
    "tslint": "3.13.0",
    "tslint-stylish": "2.1.0-beta",
    "typescript": "2.0.2",
    "walk": "2.3.9",
    "yargs": "4.8.0"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "angular2-in-memory-web-api": "^0.0.21",
    "bootstrap-datepicker": "^1.6.4",
    "core-js": "2.4.0",
    "es-module-loader": "1.0.0",
    "font-awesome": "4.6.3",
    "highcharts": "4.2.5",
    "jquery": "3.0.0",
    "moment": "2.15.0",
    "ng2-bootstrap": "1.1.5",
    "ng2-clip": "^1.0.0-alpha.2",
    "ng2-date-picker": "^0.2.1",
    "ng2-select": "^1.1.2",
    "ng2-tag-input": "^0.8.4",
    "ng2-uploader": "^1.4.1",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.38",
    "zeroclipboard": "^2.2.0",
    "zone.js": "0.6.23"
  }
```

these all,thanks :)

**Comment by Gbuomprisco** [comment]
Hi @ntfs32,

the angular dependencies are very old. Please update your package.json and reopen if still broken :)
