### ISSUE TITLE
Not working with universal CLI 

### ISSUE THREAD

**Issue by wnabil** [Gbuomprisco/ng2-tag-input#204]
Hello
I was using this before with angular cli and it works but after updating my project to universal cli the compile gives me this error :
`10% building modules 2/2 modules 0 activeError: TagInputModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:332:19)
    at /home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:345:51
    at Array.map (native)
    at AotPlugin.extractLoadChildren (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:343:14)
    at AotPlugin._processNgModule (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:272:38)
    at /home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
webpack: bundle is now INVALID.Error: TagInputModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:332:19)
    at /home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:345:51
    at Array.map (native)
    at AotPlugin.extractLoadChildren (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:343:14)
    at AotPlugin._processNgModule (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:272:38)
    at /home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
webpack: bundle is now INVALID.(node:21863) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toStrin
g' of undefined
(node:21863) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'toString' of undefined`
i am using universal cli version 1.0.0-alpha.universal.3
also tried to update to 0.8.6 or downgrade to 0.8.3 but no luck
Thanks

**Comment by Gbuomprisco** [comment]
Hi @wnabil,

I've never tried it with Universal. I'll have a look at some point.

**Comment by Gbuomprisco** [comment]
I think we can close this now?
