### ISSUE TITLE
Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by abadakhshan** [Gbuomprisco/ng2-tag-input#231]
I use tag-input with 
  <tag-input-dropdown [showDropdownIfEmpty]="true"
                                        [autocompleteObservable]='requestAutocompleteItems'>
                    </tag-input-dropdown>

sometimes after i select tag from loaded dropdown, i cant add another tag
and i get this exception:

`TypeError: Cannot read property 'focus' of undefined
    at Ng2DropdownState.select (eval at <anonymous> (http://localhost:1150/0.chunk.js:1318:1), <anonymous>:1286:14)
    at Ng2DropdownMenu.onBackspace (eval at <anonymous> (http://localhost:1150/0.chunk.js:1318:1), <anonymous>:1144:16)
    at Ng2DropdownMenu.handleKeypress (eval at <anonymous> (http://localhost:1150/0.chunk.js:1318:1), <anonymous>:976:33)
    at HTMLBodyElement.eval (eval at <anonymous> (http://localhost:1150/js/vendor.js:1182:1), <anonymous>:510:53)
    at ZoneDelegate.invokeTask (eval at 377 (http://localhost:1150/js/polyfills.js:188:1), <anonymous>:363:31)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:1150/js/vendor.js:764:1), <anonymous>:262:37)
    at ZoneDelegate.invokeTask (eval at 377 (http://localhost:1150/js/polyfills.js:188:1), <anonymous>:362:36)
    at Zone.runTask (eval at 377 (http://localhost:1150/js/polyfills.js:188:1), <anonymous>:166:47)
    at HTMLBodyElement.ZoneTask.invoke (eval at 377 (http://localhost:1150/js/polyfills.js:188:1), <anonymous>:41`

**Comment by Gbuomprisco** [comment]
Don't seem able to reproduce. Please reopen if still an issue.

**Comment by skysrc** [comment]
if you have multiple tag-input with dropdown and using tab to navigate from one tag input to another tag input.
Steps to reproduce :
1.Have 2 tag input tag with dropdown, and set  showDropdownIfEmpty to 'true'.
2.On 1st tag input tab and 'enter' to select the option item
3.Then hit 'tab'

**Comment by Gbuomprisco** [comment]
Hi @skysrc,

thanks - i will try that

**Comment by AlexTo** [comment]
hi I'm having the same issue, there is no need to set showDropdownIfEmpty to 'true' to reproduce this. I have the issue without showDropdownIfEmpty

**Comment by arjunpanicker** [comment]
Hi,

Any resolution to this problem? Even I am facing this issue and I don't know how to fix this.
