### ISSUE TITLE
Ionic 2 Build Errors

### ISSUE THREAD

**Issue by danielehrhardt** [Gbuomprisco/ng2-tag-input#283]
Hi i got this Build Errors at my Ionic 2 Application 

```
[04:21:57]  build prod failed: Template parse errors: Can't bind to 'inputText' since it isn't a known property of
            'tag-input-form'. 1. If 'tag-input-form' is an Angular component and it has 'inputText' input, then verify
            that it is part of this module. 2. If 'tag-input-form' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA"
            to the '@NgModule.schemas' of this component to suppress this message. (" (onKeyup)="fireEvents('keyup',
            $event)" [ERROR ->][(inputText)]="inputText" [validators]="validators" "): TagInputComponent@38:12
[04:21:57]  ionic-app-script task: "build"
[04:21:57]  Error: Template parse errors: Can't bind to 'inputText' since it isn't a known property of 'tag-input-form'.
            1. If 'tag-input-form' is an Angular component and it has 'inputText' input, then verify that it is part of
            this module. 2. If 'tag-input-form' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the
            '@NgModule.schemas' of this component to suppress this message. (" (onKeyup)="fireEvents('keyup', $event)"
            [ERROR ->][(inputText)]="inputText" [validators]="validators" "): TagInputComponent@38:12
Error: Template parse errors:
Can't bind to 'inputText' since it isn't a known property of 'tag-input-form'.
1. If 'tag-input-form' is an Angular component and it has 'inputText' input, then verify that it is part of this module.
2. If 'tag-input-form' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            (onKeyup)="fireEvents('keyup', $event)"

            [ERROR ->][(inputText)]="inputText"

            [validators]="validators"
"): TagInputComponent@38:12
    at SyntaxError.BaseError [as constructor] (/Users/danielehrhardt/projekte/netz-app/node_modules/@angular/compiler/bundles/compiler.umd.js:1597:31)
    at new SyntaxError (/Users/danielehrhardt/projekte/netz-app/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at TemplateParser.parse (/Users/danielehrhardt/projekte/netz-app/node_modules/@angular/compiler/bundles/compiler.umd.js:11444:23)
    at AotCompiler._compileComponent (/Users/danielehrhardt/projekte/netz-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24815:72)
    at /Users/danielehrhardt/projekte/netz-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24717:117
    at Array.forEach (native)
    at AotCompiler._compileSrcFile (/Users/danielehrhardt/projekte/netz-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24701:24)
    at /Users/danielehrhardt/projekte/netz-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24676:95
    at Array.map (native)
    at /Users/danielehrhardt/projekte/netz-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24676:60
```

**Comment by Gbuomprisco** [comment]
very odd, @Input() inputText is there.

**Comment by danielehrhardt** [comment]
You can reproduce if you you create a new ionic app 
[Ionic 2](https://github.com/driftyco/ionic2-app-base)
and add this package

Thank you for your fast reply

**Comment by Gbuomprisco** [comment]
Yeah can reproduce it, when building prod. Still, very odd :|

**Comment by Gbuomprisco** [comment]
Hi @danielehrhardt,

can you try with the new version? seems to build fine for me

**Comment by dkd051** [comment]
I have the same problem on ionic2

**Comment by Gbuomprisco** [comment]
@dkd051 can you create a new issue and fill out the template? to get a better understanding of your issue :)
