### ISSUE TITLE
angular-cli error

### ISSUE THREAD

**Issue by FallenRiteMonk** [Gbuomprisco/ng2-tag-input#29]
i get the following error when i do a angular-cli production build after upgrading from version 0.1.3 to 0.2.1:

```
Build failed.
The Broccoli Plugin: [BundlePlugin] failed with:
Error on dependency parsing for vendor/ng2-tag-input/dist/ng2-tag-input.bundle.js at file:///<PATH>/tmp/bundle_plugin-input_base_path-eXqLvrqq.tmp/0/vendor/ng2-tag-input/dist/ng2-tag-input.bundle.js
        Loading vendor/ng2-tag-input/index.js
        <LOADING MULTIPLE CUSTOM FILES>
        Loading app/index.js
        Loading main.js
        Error: Multiple anonymous defines.
    at ParseTreeTransformer.AMDDependenciesTransformer.transformCallExpression (<PATH>/node_modules/angular-cli/node_modules/systemjs-builder/compilers/amd.js:98:13)
    at CallExpression.$__super.transform (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:6948:28)
    at ParseTreeTransformer.transformAny (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9514:44)
    at ParseTreeTransformer.transformExpressionStatement (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9825:31)
    at ExpressionStatement.$__super.transform (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:7419:28)
    at ParseTreeTransformer.transformAny (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9514:44)
    at ParseTreeTransformer.transformToBlockOrStatement (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9538:32)
    at ParseTreeTransformer.transformIfStatement (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9955:29)
    at IfStatement.$__super.transform (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:7737:28)
    at ParseTreeTransformer.transformAny (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9514:44)
    at ParseTreeTransformer.transformToBlockOrStatement (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9538:32)
    at ParseTreeTransformer.transformIfStatement (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9956:31)
    at IfStatement.$__super.transform (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:7737:28)
    at ParseTreeTransformer.transformAny (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9514:44)
    at ParseTreeTransformer.transformList (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9521:34)
    at ParseTreeTransformer.transformFunctionBody (<PATH>/node_modules/angular-cli/node_modules/traceur/bin/traceur.js:9895:31)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (<PATH>/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (<PATH>/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BundlePlugin (<PATH>/node_modules/angular-cli/lib/broccoli/angular-broccoli-bundle.js:11:5)
    at Angular2App._getBundleTree (<PATH>/node_modules/angular-cli/lib/broccoli/angular2-app.js:437:22)
    at Angular2App._buildTree (<PATH>/node_modules/angular-cli/lib/broccoli/angular2-app.js:160:21)
    at new Angular2App (<PATH>/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (<PATH>/angular-cli-build.js:13:13)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (<PATH>/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (<PATH>/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (<PATH>/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (<PATH>/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at <PATH>/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (<PATH>/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (<PATH>/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at <PATH>/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (<PATH>/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

I dont know if its your problem or not, but if you can somehow fix it I would be pleased.
I'm using angular-cli beta.10

If you need more info just let me know.

Thanks

**Comment by Gbuomprisco** [comment]
Hi @FallenRiteMonk, I will have a look soon :)

**Comment by FallenRiteMonk** [comment]
Angular is changing to use webpack where this error does no longer appear.
I tested this with the angular-cli@1.0.0-beta.11-webpack.8.
Even though this is not yet an official beta release, it works, and will for sure come sooner or later, therefor I think this issue can be closed!

**Comment by Gbuomprisco** [comment]
Cool thanks :)
