### ISSUE TITLE
ng-template issue while bootstrap

### ISSUE THREAD

**Issue by pravin-git** [Gbuomprisco/ng2-tag-input#334]
**Getting 'ng-template' is not a known element: error when bootstrapping the application**  

I have --
1. installed angular 4 
2. followed all steps like npm install ng2-tag-input --save 
3. made necessary changes in Systemjs.config

Here are my SystemJs.Config changes

```
// map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'rxjs':                       'node_modules/rxjs',
    'ng2-tag-input':              '/node_modules/ng2-tag-input'
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'ng2-tag-input':              { main: 'dist/ng2-tag-input.bundle.js', defaultExtension: 'js' },
    'ng2-material-dropdown':      { defaultExtension: 'js', main: 'dist/ng2-dropdown.bundle.js'},
    'ng2-tag-input/modules/components/tag-input.template.html': { defaultJSExtension: false }
  };
```

Here are the dependencies
```
"dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "@angular/upgrade": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/platform-server": "4.0.0",
    "@angular/tsc-wrapped": "4.0.0",
    "@angular/animations": "4.0.0",

    "systemjs": "0.19.47",
    "core-js": "2.4.1",
    "rxjs": "5.2.0",
    "zone.js": "0.8.5"
  },
  "devDependencies": {
    "concurrently": "3.4.0",
    "lite-server": "2.3.0",
    "typescript": "2.2.1",
    "@types/node": "7.0.11"
  }
```
Here is complete stack trace

```
Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("tchCase="true" [attr.contenteditable]="editModeActivated">
        <!-- CUSTOM TEMPLATE -->
        [ERROR ->]<ng-template
            [ngOutletContext]="{ item: model, index: index }"
            [ngTemplateOut"): TagComponent@11:8
    at SyntaxError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:1597:31) [<root>]
    at new SyntaxError (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:1795:20) [<root>]
    at TemplateParser.parse (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:11444:23) [<root>]
    at JitCompiler._compileTemplate (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:27557:72) [<root>]
    at eval (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:27440:66) [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler._compileComponents (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:27440:23) [<root>]
    at createResult (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:27322:23) [<root>]
    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:113:43) [<root> => <root>]
    at http://localhost:3000/node_modules/zone.js/dist/zone.js:520:57 [<root>]
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:418:35) [<root>]
```

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Sorry but ng-template replaces template in v4. Check out the version attached to your root element. I don't know think you're going to see 4.0.0
