### ISSUE TITLE
SystemJS builder error

### ISSUE THREAD

**Issue by Fagertveit** [Gbuomprisco/ng2-tag-input#69]
Hi. and thank you for bringing this awesome module to angular 2.

I'm having some problems when I try to build my application with the Systemjs builder, it seems like there's some define errors when importing the module to the build process. I am able to use the module during development (typescript compiles correctly and such) but when I try to make a build it throws the following error:

> Unhandled rejection Error on dependency parsing for npm:ng2-tag-input/dist/ng2-tag-input.bundle.js at file:///C:/dev/tagModuleTest/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js
> 
> ```
>     Loading app/app.module.js
>     Loading app/main.js
>     Error: Multiple anonymous defines.
> ```

I've tested this by using a barebone quickstart project from angular to get the bare minimum, I'll zip it down and attach it here for reference.

As angular 2 is pretty new (especially the final release) it's quite hard to get some definitive answers on what is wrong here, I'll try to dig a bit deeper into this and will follow up if I get any eureka moments.

Best Regards,
/ Glenn
[tagModuleTest.zip](https://github.com/Gbuomprisco/ng2-tag-input/files/507766/tagModuleTest.zip)

**Comment by Gbuomprisco** [comment]
Hi @Fagertveit, thanks, I'll have a look. SystemJS is giving me a lot of headaches lately :)

**Comment by johntzan** [comment]
having the same problem here, also newest version 0.4.4 does not work at all with systemjs.

**Comment by Gbuomprisco** [comment]
Hi @johntzan,

Can you post here your systemjs config please?Thanks

**Comment by TakeN0** [comment]
Having the same issue

`Error on dependency parsing for ng2-tag-input at file:///Users/ej049491/Documents/infinity/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js
	Loading dist/tmp/web.module.js
	Loading dist/tmp/main.web.js
	Error: Multiple anonymous defines.
    at ParseTreeTransformer.AMDDependenciesTransformer.transformCallExpression (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/compilers/amd.js:98:13)
    at CallExpression.transform (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:6948:28)
    at ParseTreeTransformer.transformAny (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9514:44)
    at ParseTreeTransformer.transformExpressionStatement (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9825:31)
    at ExpressionStatement.transform (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7419:28)
    at ParseTreeTransformer.transformAny (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9514:44)
    at ParseTreeTransformer.transformToBlockOrStatement (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9538:32)
    at ParseTreeTransformer.transformIfStatement (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9955:29)
    at IfStatement.transform (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7737:28)
    at ParseTreeTransformer.transformAny (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9514:44)
    at ParseTreeTransformer.transformToBlockOrStatement (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9538:32)
    at ParseTreeTransformer.transformIfStatement (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9956:31)
    at IfStatement.transform (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7737:28)
    at ParseTreeTransformer.transformAny (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9514:44)
    at ParseTreeTransformer.transformList (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9521:34)
    at ParseTreeTransformer.transformFunctionBody (/Users/ej049491/Documents/infinity/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9895:31)
`

My systemjs config.

`SYSTEM_BUILDER_CONFIG: any = {
    defaultJSExtensions: true,
    packageConfigPaths: [
      join(this.PROJECT_ROOT, 'node_modules', '*', 'package.json'),
      join(this.PROJECT_ROOT, 'node_modules', '@angular', '*', 'package.json')
    ],
    paths: {
      [`${this.TMP_DIR}/*`]: `${this.TMP_DIR}/*`,
      '*': 'node_modules/*'
    },
    packages: {
      '@angular/common': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/compiler': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/core/testing': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/core': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/forms': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/http': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser-dynamic': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/router': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      'rxjs': {
        defaultExtension: 'js'
      },
      '@ngrx/core': {
        main: 'bundles/core.umd.js',
        defaultExtension: 'js'
      },
      '@ngrx/store': {
        main: 'bundles/store.umd.js',
        defaultExtension: 'js'
      },
      'primeng': {
        main: 'primeng.js',
        defaultExtension: 'js'
      },
      'ng2-tag-input': {
        main: 'dist/ng2-tag-input.bundle.js',
        defaultExtension: 'js',
      }
    }
  };`

**Comment by johntzan** [comment]
@Gbuomprisco So newest version is working now, i had it looking for dist/index.js (which would cause it to look for dist/dist/ng2-tag-input.bundle.js which does not exist) instead of dist/ng2-tag-input.bundle.js directly. But the builder is giving the exact same error as the other two mentioned on this thread: Error: Multiple anonymous defines

**Comment by Gbuomprisco** [comment]
I read similar issues at https://github.com/InfomediaLtd/angular2-materialize/issues/115

It seems like it was fixed by adding "format": "global" to the configuration. I have not encountered this issue, I rarely use SystemJS to be honest. Can you try and let me know if this works?

Thanks!

**Comment by TakeN0** [comment]
Adding "format": "global" to the configuration let me build but now I run into runtime errors.

`localhost/:79 Error: (SystemJS) Cannot read property 'Component' of undefined
	TypeError: Cannot read property 'Component' of undefined
	    at eval (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:142:16)
	    at Object.module.exports (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:149:3)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:30:30)
	    at Object.c (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:119:11)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:30:30)
	    at Object.module.exports (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:68:15)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:30:30)
	    at c (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:50:18)
	    at eval (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:53:10)
	    at webpackUniversalModuleDefinition (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:9:27)
	Evaluating http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js
	Evaluating http://localhost:5555/app/settings/settings.component.js
	Evaluating http://localhost:5555/web.module.js
	Evaluating http://localhost:5555/main.web.js
	Error loading http://localhost:5555/main.web.js
	    at eval (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:142:16)
	    at Object.module.exports (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:149:3)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:30:30)
	    at Object.c (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:119:11)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:30:30)
	    at Object.module.exports (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:68:15)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:30:30)
	    at c (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:50:18)
	    at eval (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:53:10)
	    at webpackUniversalModuleDefinition (http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js:9:27)
	Evaluating http://localhost:5555/node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js
	Evaluating http://localhost:5555/app/settings/settings.component.js
	Evaluating http://localhost:5555/web.module.js
	Evaluating http://localhost:5555/main.web.js
	Error loading http://localhost:5555/main.web.js`

**Comment by sumitdhameja** [comment]
@TakeN0 Just wondering whether the build worked for you, Im getting runtime error after adding "format":"global". Uncaught TypeError: Cannot read property 'Component' of undefined(…).

**Comment by TakeN0** [comment]
@sumitdhameja I am seeing the same behavior you are.

**Comment by iredkin** [comment]
+1

**Comment by marcoskichel** [comment]
Any news on this?

**Comment by Taffatech** [comment]
I am also getting the issue: Cannot read property 'Component' of undefined(…).

**Comment by Gbuomprisco** [comment]
Hi everyone,

I was able to make it work with systemjs. Could you try setting `format: 'cjs'`?

**Comment by johntzan** [comment]
can confirm format: cjs along with the other instructions on the readme worked. Thanks!
