### ISSUE TITLE
Cannot resolve ./icon.html

### ISSUE THREAD

**Issue by jaysson** [Gbuomprisco/ng2-tag-input#80]
I am trying to use this with ionic 2, but getting following error.

```
Error: Could not resolve './icon.html' from /Users/jaysson/Desktop/pollzapp/node_modules/ng2-tag-input/dist/modules/components/icon/icon.js
    at Error (native)
    at /Users/jaysson/Desktop/pollzapp/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/jaysson/Desktop/pollzapp/node_modules/browser-resolve/index.js:265:24
    at /Users/jaysson/Desktop/pollzapp/node_modules/resolve/lib/async.js:55:18
    at load (/Users/jaysson/Desktop/pollzapp/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/jaysson/Desktop/pollzapp/node_modules/resolve/lib/async.js:92:31)
    at /Users/jaysson/Desktop/pollzapp/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

I see `template: require('./icon.html')` in icon.js, but there is no icon.html.

**Comment by Gbuomprisco** [comment]
Hi @jaysson,

Not sure how this is happening honestly, I haven't tried it with Ionic. Do you have any minimal repo I can check this on? Thanks

**Comment by msegers** [comment]
Heya,

got this aswell on a regular webpack project

```
ERROR in ./~/ng2-tag-input/dist/modules/components/tag-input.js
Module not found: Error: Can't resolve './tag-input.style.scss' in '/Users/mathijs/projects/customer-care/node_modules/ng2-tag-input/dist/modules/components'
 @ ./~/ng2-tag-input/dist/modules/components/tag-input.js 261:21-54
 @ ./~/ng2-tag-input/dist/modules/components/index.js
 @ ./~/ng2-tag-input/dist/modules/ng2-tag-input.module.js
 @ ./src/app/modules/newsletter/newsletter.module.ts
 @ ./src/app/modules/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2-tag-input/dist/modules/components/tag-input.js
Module not found: Error: Can't resolve './tag-input.template.html' in '/Users/mathijs/projects/customer-care/node_modules/ng2-tag-input/dist/modules/components'
 @ ./~/ng2-tag-input/dist/modules/components/tag-input.js 262:22-58
 @ ./~/ng2-tag-input/dist/modules/components/index.js
 @ ./~/ng2-tag-input/dist/modules/ng2-tag-input.module.js
 @ ./src/app/modules/newsletter/newsletter.module.ts
 @ ./src/app/modules/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2-tag-input/dist/modules/components/icon/icon.js
Module not found: Error: Can't resolve './icon.html' in '/Users/mathijs/projects/customer-care/node_modules/ng2-tag-input/dist/modules/components/icon'
 @ ./~/ng2-tag-input/dist/modules/components/icon/icon.js 19:22-44
 @ ./~/ng2-tag-input/dist/modules/components/icon/index.js
 @ ./~/ng2-tag-input/dist/modules/ng2-tag-input.module.js
 @ ./src/app/modules/newsletter/newsletter.module.ts
 @ ./src/app/modules/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2-tag-input/dist/modules/components/tag-input-form/tag-input-form.component.js
Module not found: Error: Can't resolve './tag-input-form.template.html' in '/Users/mathijs/projects/customer-care/node_modules/ng2-tag-input/dist/modules/components/tag-input-form'
 @ ./~/ng2-tag-input/dist/modules/components/tag-input-form/tag-input-form.component.js 94:22-63
 @ ./~/ng2-tag-input/dist/modules/components/tag-input-form/index.js
 @ ./~/ng2-tag-input/dist/modules/ng2-tag-input.module.js
 @ ./src/app/modules/newsletter/newsletter.module.ts
 @ ./src/app/modules/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main
```

**Comment by msegers** [comment]
So I've been looking at the package. I see no HTML nor CSS. So I guess the npm package is wrong.

![screen shot 2016-10-25 at 10 00 38](https://cloud.githubusercontent.com/assets/3832687/19677507/f1310700-9a99-11e6-8695-fdc35637f24e.png)

**Comment by Gbuomprisco** [comment]
Hi @msegers,

very odd, must be something with Webpack maybe. Ill have a look, even though it will be odd without being able to reproduce. A minimal repo/plunker will help a lot!

**Comment by zoltanbalog** [comment]
@jaysson & @msegers how do you import this package in your app module? I was get similar error, try to this "import { TagInputModule } from 'ng2-tag-input';"

**Comment by msegers** [comment]
That's what I tried, when that goes wrong I'm no longer of interest and I
wrote something else.

Anyways Chips should be in material alpha 11 or 12
